# Generated by Django 3.0.6 on 2020-05-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Variant'),
        ),
    ]
