# Generated by Django 3.0.6 on 2020-06-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200620_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parents_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='parents_phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='phone'),
        ),
    ]
